# Generated by Django 2.1.4 on 2018-12-27 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aricle', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aricle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='摘要')),
                ('content', models.TextField(help_text='目前支持markdown', verbose_name='内容')),
                ('html', models.TextField(default='', verbose_name='渲染后的格式')),
                ('uv', models.PositiveIntegerField(default=0, verbose_name='uv')),
                ('pv', models.PositiveIntegerField(default=0, verbose_name='pv')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aricle.Category', verbose_name='分类')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('tags', models.ManyToManyField(related_name='posts', to='aricle.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-id'],
            },
        ),
    ]
