# Generated by Django 2.1.5 on 2019-07-26 18:23

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aricle', '0002_auto_20190725_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aricle',
            name='content',
            field=simditor.fields.RichTextField(verbose_name='内容'),
        ),
    ]
