# Generated by Django 2.1.5 on 2019-07-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='git_path',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Git地址'),
        ),
    ]
